runtime: php
env : flex
runtime_config :
  document_root: public
  enable_stackdriver_integration: true

skip_files:it
  - .env

env_variables:
  LOG_CHANNEL: stackdriver
  APP_KEY: base64:DDU+MHxEX3plnt3MMpBzn+RibAyg68m8SvAnHVHceBc=
